import React from 'react';
import { cn } from '@/lib/utils';
import {
    Activity,
    AlertCircle,
    AlertTriangle,
    AlignCenter,
    AlignLeft,
    AlignRight,
    Archive,
    ArrowDown,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftRight,
    ArrowRight,
    ArrowRightLeft,
    ArrowUp,
    ArrowUpDown,
    ArrowUpRight,
    AtSign,
    Award,
    BarChart3,
    Bell,
    Bold,
    Book,
    BookOpen,
    Bookmark,
    BookmarkCheck,
    Briefcase,
    Building,
    Building2,
    Calendar,
    CalendarDays,
    Camera,
    Check,
    CheckCircle2,
    CheckSquare,
    CheckSquare2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    ChevronsUpDown,
    Circle,
    Clock,
    CloudUpload,
    Code,
    Coins,
    Columns,
    Columns3,
    Compass,
    Copy,
    CornerDownLeft,
    CornerUpLeft,
    Crosshair,
    Database,
    Diff,
    DollarSign,
    Download,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileCheck,
    FileCode,
    FileDown,
    FileEdit,
    FileIcon,
    FileJson,
    FilePlus,
    FilePlus2,
    FileSignature,
    FileSpreadsheet,
    FileText,
    FileType,
    FileUp,
    FileX,
    Filter,
    Fingerprint,
    Flag,
    Folder,
    FolderClosed,
    FolderInput,
    FolderOpen,
    FolderPlus,
    FolderSearch,
    FolderSync,
    FolderTree,
    Gavel,
    GitBranch,
    GitCommit,
    GitFork,
    Globe,
    Grid,
    GripVertical,
    Handshake,
    Hash,
    Heading1,
    Heading2,
    HelpCircle,
    History,
    IdCard,
    Image,
    Info,
    Italic,
    Key,
    KeyRound,
    Landmark,
    Languages,
    Layers,
    Layout,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    LayoutTemplate,
    Link,
    Link2,
    List,
    ListFilter,
    ListOrdered,
    ListTree,
    Loader2,
    LoaderCircle,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Maximize2,
    Menu,
    MessageSquare,
    Minimize2,
    MinusSquare,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    Navigation,
    Network,
    Palette,
    PanelLeft,
    PanelLeftClose,
    PanelLeftOpen,
    Paperclip,
    PenTool,
    Pencil,
    Percent,
    Pin,
    Play,
    Plus,
    PlusCircle,
    Power,
    PowerOff,
    Printer,
    Quote,
    Receipt,
    Redo,
    RefreshCcw,
    RefreshCw,
    RotateCcw,
    Ruler,
    Save,
    Scale,
    ScanEye,
    ScanLine,
    Scissors,
    Search,
    Send,
    Settings,
    Settings2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    Sliders,
    SlidersHorizontal,
    Smartphone,
    Smile,
    Sparkles,
    Square,
    Star,
    Strikethrough,
    Sun,
    Table,
    Tag,
    Tags,
    Target,
    Timer,
    Trash2,
    Truck,
    Type,
    Undo,
    Unlock,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserCircle,
    UserCog,
    UserPen,
    UserPlus,
    UserX,
    Users,
    Verified,
    Workflow,
    X,
    XCircle,
    Zap,
    type LucideIcon,
    type LucideProps,
} from 'lucide-react';

export const Icons = {
    Activity,
    AlertCircle,
    AlertTriangle,
    AlignCenter,
    AlignLeft,
    AlignRight,
    Archive,
    ArrowDown,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftRight,
    ArrowRight,
    ArrowRightLeft,
    ArrowUp,
    ArrowUpDown,
    ArrowUpRight,
    AtSign,
    Award,
    BarChart3,
    Bell,
    Bold,
    Book,
    BookOpen,
    Bookmark,
    BookmarkCheck,
    Briefcase,
    Building,
    Building2,
    Calendar,
    CalendarDays,
    Camera,
    Check,
    CheckCircle2,
    CheckSquare,
    CheckSquare2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    ChevronsUpDown,
    Circle,
    Clock,
    CloudUpload,
    Code,
    Coins,
    Columns,
    Columns3,
    Compass,
    Copy,
    CornerDownLeft,
    CornerUpLeft,
    Crosshair,
    Database,
    Diff,
    DollarSign,
    Download,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileCheck,
    FileCode,
    FileDown,
    FileEdit,
    FileIcon,
    FileJson,
    FilePlus,
    FilePlus2,
    FileSignature,
    FileSpreadsheet,
    FileText,
    FileType,
    FileUp,
    FileX,
    Filter,
    Fingerprint,
    Flag,
    Folder,
    FolderClosed,
    FolderInput,
    FolderOpen,
    FolderPlus,
    FolderSearch,
    FolderSync,
    FolderTree,
    Gavel,
    GitBranch,
    GitCommit,
    GitFork,
    Globe,
    Grid,
    GripVertical,
    Handshake,
    Hash,
    Heading1,
    Heading2,
    HelpCircle,
    History,
    IdCard,
    Image,
    Info,
    Italic,
    Key,
    KeyRound,
    Landmark,
    Languages,
    Layers,
    Layout,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    LayoutTemplate,
    Link,
    Link2,
    List,
    ListFilter,
    ListOrdered,
    ListTree,
    Loader2,
    LoaderCircle,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Maximize2,
    Menu,
    MessageSquare,
    Minimize2,
    MinusSquare,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    Navigation,
    Network,
    Palette,
    PanelLeft,
    PanelLeftClose,
    PanelLeftOpen,
    Paperclip,
    PenTool,
    Pencil,
    Percent,
    Pin,
    Play,
    Plus,
    PlusCircle,
    Power,
    PowerOff,
    Printer,
    Quote,
    Receipt,
    Redo,
    RefreshCcw,
    RefreshCw,
    RotateCcw,
    Ruler,
    Save,
    Scale,
    ScanEye,
    ScanLine,
    Scissors,
    Search,
    Send,
    Settings,
    Settings2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    Sliders,
    SlidersHorizontal,
    Smartphone,
    Smile,
    Sparkles,
    Square,
    Star,
    Strikethrough,
    Sun,
    Table,
    Tag,
    Tags,
    Target,
    Timer,
    Trash2,
    Truck,
    Type,
    Undo,
    Unlock,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserCircle,
    UserCog,
    UserPen,
    UserPlus,
    UserX,
    Users,
    Verified,
    Workflow,
    X,
    XCircle,
    Zap,
} as const;

export type IconName = keyof typeof Icons;

function normalizeIconName(name: string): string {
    return name
        .replace(/[-_ ]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
        .replace(/^(.)/, (c) => c.toUpperCase());
}

export function getIcon(
    name?: string | IconName | null,
    fallback: LucideIcon = Icons.LayoutGrid,
): LucideIcon {
    if (!name) return fallback;
    if (typeof name !== 'string') return fallback;

    if (name in Icons) {
        return (Icons as Record<string, LucideIcon>)[name];
    }

    const pascal = normalizeIconName(name);
    if (pascal in Icons) {
        return (Icons as Record<string, LucideIcon>)[pascal];
    }

    const lower = name.toLowerCase().replace(/[-_ ]/g, '');
    const foundKey = Object.keys(Icons).find((k) => k.toLowerCase() === lower);
    if (foundKey) {
        return (Icons as Record<string, LucideIcon>)[foundKey];
    }

    return fallback;
}

export interface AppIconProps extends Omit<LucideProps, 'ref'> {
    name?: IconName | string | LucideIcon | null;
    fallback?: LucideIcon;
    size?: number | string;
    className?: string;
}

export const AppIcon = React.forwardRef<SVGSVGElement, AppIconProps>(
    ({ name, fallback = Icons.LayoutGrid, size = 16, className, ...props }, ref) => {
        let IconComponent: LucideIcon;

        if (typeof name === 'function' || (typeof name === 'object' && name !== null)) {
            IconComponent = name as LucideIcon;
        } else {
            IconComponent = getIcon(name, fallback);
        }

        return <IconComponent ref={ref} size={size} className={cn('shrink-0', className)} {...props} />;
    },
);

AppIcon.displayName = 'AppIcon';

export default AppIcon;
